pipeline {
    agent any
       
    stages {
        stage('Build') {
           
                sh 'mvn -B -DskipTests clean package'
            
        }
        stage('Test') {
           
                sh 'mvn test'
        }
            stage('POst'){
                    junit 'target/surefire-reports/*.xml'
                }
            
        
        stage('Deliver') {
            
                sh './jenkins/scripts/deliver.sh'
            
        }
    }
}
